name: cs7150
channels:
  - pytorch
  - huggingface
  - defaults
dependencies:
  - python=3.10.6
  - pip=21.2.4
  - cudatoolkit=11.3.1
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.23.1
  - jupyter=1.0.0
  - matplotlib=3.5.1
  - spacy=3.3.1
  - wandb=0.13.1
  - protobuf=3.19.4
  - pip:
    - albumentations>=0.4.3
    - diffusers>=0.2.4
    - opencv-python>=4.5.5.64
    - pudb>=2019.2
    - invisible-watermark>=0.1.5
    - imageio>=2.9.0
    - imageio-ffmpeg>=0.4.2
    - pytorch-lightning>=1.4.2
    - omegaconf>=2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops>=0.3.0
    - torch-fidelity>=0.3.0
    - transformers>=4.19.2
    - torchmetrics>=0.6.0
    - kornia>=0.6
    - git+https://github.com/davidbau/baukit@main#egg=baukit
    - git+https://github.com/openai/CLIP.git@main#egg=clip
    - git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - git+https://github.com/CompVis/stable-diffusion.git@main#egg=latent-diffusion
